export const permissions = {
  global: {
    UPDATE_VERSION: 'UPDATE_VERSION',
  },
  post: {
    POST_CREATE: 'POST_CREATE',
    POST_UPDATE: 'POST_UPDATE',
    POST_DELETE: 'POST_DELETE',
    POST_PUBLISH_POST: 'POST_PUBLISH_POST',
  },
  category: {
    CATEGORY_CREATE: 'CATEGORY_CREATE',
    CATEGORY_UPDATE: 'CATEGORY_UPDATE',
    CATEGORY_DELETE: 'CATEGORY_DELETE',
  },
  media: {
    MEDIA_CREATE: 'MEDIA_CREATE',
    MEDIA_UPDATE: 'MEDIA_UPDATE',
    MEDIA_DELETE: 'MEDIA_DELETE',
  },
  option: {
    OPTION_CREATE: 'OPTION_CREATE',
    OPTION_UPDATE: 'OPTION_UPDATE',
    OPTION_DELETE: 'OPTION_DELETE',
  },
  hashtag: {
    HASHTAG_CREATE: 'HASHTAG_CREATE',
    HASHTAG_UPDATE: 'HASHTAG_UPDATE',
    HASHTAG_DELETE: 'HASHTAG_DELETE',
  },
  followalong: {
    FOLLOWALONG_CREATE: 'FOLLOWALONG_CREATE',
    FOLLOWALONG_UPDATE: 'FOLLOWALONG_UPDATE',
    FOLLOWALONG_DELETE: 'FOLLOWALONG_DELETE',
  },
  banner: {
    BANNER_CREATE: 'BANNER_CREATE',
    BANNER_UPDATE: 'BANNER_UPDATE',
    BANNER_DELETE: 'BANNER_DELETE',
  },
  search: {
    SEARCH_MANAGE: 'SEARCH_MANAGE',
  },
  google: {
    GOOGLE_ANALYTIC_TOKEN: 'GOOGLE_ANALYTIC_TOKEN',
    GOOGLE_ANALYTIC_SETTING: 'GOOGLE_ANALYTIC_SETTING',
    GOOGLE_ANALYTIC_REPORT: 'GOOGLE_ANALYTIC_REPORT',
    GOOGLE_WEBMASTER_SETTING: 'GOOGLE_WEBMASTER_SETTING',
    GOOGLE_WEBMASTER_REPORT: 'GOOGLE_WEBMASTER_REPORT',
    GOOGLE_ACTIVE_PAGE: 'GOOGLE_ACTIVE_PAGE',
  },
  group: {
    CREATE_ROLE: 'CREATE_ROLE',
    USER_MANAGE: 'USER_MANAGE',
  },
};
