export const permissions = {
  global: {
    OVERVIEW: 'OVERVIEW',
    UPDATE_VERSION: 'UPDATE_VERSION',
    GENERAL_VIEW: 'GENERAL_VIEW',
    GENERAL_UPDATE: 'GENERAL_UPDATE',
  },
  post: {
    POST_VIEW: 'POST_VIEW',
    POST_MANAGE: 'POST_MANAGE',
    POST_CREATE: 'POST_CREATE',
    POST_UPDATE: 'POST_UPDATE',
    POST_DELETE: 'POST_DELETE',
    POST_PUBLISH_POST: 'POST_PUBLISH_POST',
  },
  category: {
    CATEGORY_VIEW: 'CATEGORY_VIEW',
    CATEGORY_MANAGE: 'CATEGORY_MANAGE',
    CATEGORY_CREATE: 'CATEGORY_CREATE',
    CATEGORY_UPDATE: 'CATEGORY_UPDATE',
    CATEGORY_DELETE: 'CATEGORY_DELETE',
  },
  comment: {
    COMMENT_VIEW: 'COMMENT_VIEW',
    COMMENT_MANAGE: 'COMMENT_MANAGE',
    COMMENT_CREATE: 'COMMENT_CREATE',
    COMMENT_UPDATE: 'COMMENT_UPDATE',
    COMMENT_DELETE: 'COMMENT_DELETE',
  },
  media: {
    MEDIA_VIEW: 'MEDIA_VIEW',
    MEDIA_MANAGE: 'MEDIA_MANAGE',
    MEDIA_CREATE: 'MEDIA_CREATE',
    MEDIA_UPDATE: 'MEDIA_UPDATE',
    MEDIA_DELETE: 'MEDIA_DELETE',
  },
  option: {
    OPTION_VIEW: 'OPTION_VIEW',
    OPTION_MANAGE: 'OPTION_MANAGE',
    OPTION_CREATE: 'OPTION_CREATE',
    OPTION_UPDATE: 'OPTION_UPDATE',
    OPTION_DELETE: 'OPTION_DELETE',
  },
  hashtag: {
    HASHTAG_VIEW: 'HASHTAG_VIEW',
    HASHTAG_MANAGE: 'HASHTAG_MANAGE',
    HASHTAG_CREATE: 'HASHTAG_CREATE',
    HASHTAG_UPDATE: 'HASHTAG_UPDATE',
    HASHTAG_DELETE: 'HASHTAG_DELETE',
  },
  followalong: {
    FOLLOWALONG_VIEW: 'FOLLOWALONG_VIEW',
    FOLLOWALONG_MANAGE: 'FOLLOWALONG_MANAGE',
    FOLLOWALONG_CREATE: 'FOLLOWALONG_CREATE',
    FOLLOWALONG_UPDATE: 'FOLLOWALONG_UPDATE',
    FOLLOWALONG_DELETE: 'FOLLOWALONG_DELETE',
  },
  banner: {
    BANNER_VIEW: 'BANNER_VIEW',
    BANNER_MANAGE: 'BANNER_MANAGE',
    BANNER_CREATE: 'BANNER_CREATE',
    BANNER_UPDATE: 'BANNER_UPDATE',
    BANNER_DELETE: 'BANNER_DELETE',
  },
  search: {
    SEARCH_VIEW: 'SEARCH_VIEW',
    SEARCH_MANAGE: 'SEARCH_MANAGE',
  },
  google: {
    GOOGLE_ANALYTIC_TOKEN: 'GOOGLE_ANALYTIC_TOKEN',
    GOOGLE_ANALYTIC_SETTING: 'GOOGLE_ANALYTIC_SETTING',
    GOOGLE_ANALYTIC_REPORT: 'GOOGLE_ANALYTIC_REPORT',
    GOOGLE_WEBMASTER_SETTING: 'GOOGLE_WEBMASTER_SETTING',
    GOOGLE_WEBMASTER_REPORT: 'GOOGLE_WEBMASTER_REPORT',
    GOOGLE_ACTIVE_PAGE: 'GOOGLE_ACTIVE_PAGE',
  },
  group: {
    CREATE_ROLE: 'CREATE_ROLE',
    USER_MANAGE: 'USER_MANAGE',
  },
  design: {
    DESIGN_VIEW: 'DESIGN_VIEW',
  },
  connection: {
    CONNECTION_VIEW: 'CONNECTION_VIEW',
  },
  custom: {
    CUSTOM_VIEW: 'CUSTOM_VIEW',
  },
  shortlink: {
    SHORTLINK_VIEW: 'SHORTLINK_VIEW',
  },
  phrase: {
    PHRASE_VIEW: 'PHRASE_VIEW',
  },
  theme: {
    THEME_VIEW: 'THEME_VIEW',
    THEME_INSTALL: 'THEME_INSTALL',
  },
};
